### PR TITLE
If prompt.message is disabled, don't show extra delimiter at the beginning of the line

### PR DESCRIPTION
**Pull request by Olegas**

### CODE REVIEW

**Comment by Sequoia** [comment]
:+1:
Is this project actively maintained? This option seems like a no-brainer...

**Comment by Sequoia** [comment]
fdgj 467u5e67b24w6ejy5d7k46859ypiu[o0;p-]'80[=\
k-/l;+=[
']

**Comment by diosney** [comment]
I really don't know :( it will be a shame if so, I use this in a couple of projects :(

**Comment by Sequoia** [comment]
I can't take it on rn unfortunately so I'd wait 'til the next time I have active need for this again, but if anyone needs the feature now, fork, publish on NPM, start taking PRs, and publicize your tool as a continuation of this tool which has clearly been abandoned.

:sparkles: The Power of Free Software Compels You! :sparkles:

**Comment by dgoguerra** [comment]
Is there a known well-maintained fork or alternative to this project? I was also looking for this functionality

**Comment by Sequoia** [comment]
Inquirer.js

**Comment by dgoguerra** [comment]
thanks! looks great

**Comment by gangstead** [comment]
I asked the admins to let me join to try to breathe some life back into this project.  Hopefully we can get a new release published to npm soon.

**Comment by alessioalex** [comment]
@gangstead Hey there! Awesome that you merged all these pull requests into master now!

One tiny suggestion: would it be much trouble if you did it from Github directly? Just asking because when you look at the project history you see a lot of 'merged from user/master' and it doesn't show the commit with the actual feature addition / bug fixed. See here: https://github.com/flatiron/prompt/commits/master (compare latest commits and then search for other 'Merge pull request' messages). Thanks!

**Comment by tuvistavie** [comment]
@gangstead Thank you very much for maintaining the project.

**Comment by gangstead** [comment]
I am doing it from github, what's happening is that I'm merging pull requests that are 6 months old so those original commits are back in the timeline with the date the author created them, way down the list.

**Comment by alessioalex** [comment]
@gangstead oh my bad, don't know what I was thinking. Again, thanks for maintaining the project!

**Comment by gangstead** [comment]
NP.  Hopefully me and any new admins who ask to join can be a little more on top of things and it won't be so confusing when the merge request is soon after the original commit.

**Pull request merged**
