### PR TITLE
promisify prompt.get

### PR DESCRIPTION
**Pull request by caub**
@gangstead Hi, could you check this very small PR?

It just promisifies `prompt.get` (if no callback passed)

it'll help for https://github.com/flatiron/prompt/issues/170

We have to do 
```js
const prompt = require('prompt');

const getPrompt = require('util').promisify(prompt.get).bind(prompt);
```

every time we use prompt, so that PR would be cool

### CODE REVIEW

**Comment by gangstead** [comment]
I'm not really active on this project any more, so I'm a little hesitant to merge the PR when the build isn't passing.

**Comment by caub** [comment]
Ah, I initially put an arrow callback, the I changed it to a function for node 0.12 https://github.com/flatiron/prompt/pull/196/commits/34658ba2052aed30006bcceb67724835a6afaa83

The CI should pass, I just don't manage to restart the CI build

**Comment by caub** [comment]
Ah, I forgot one arrow fn, thanks CI

It should pass now, sorry

**Comment by caub** [comment]
The error now https://travis-ci.org/flatiron/prompt/jobs/657864911#L322 has nothing to do with this PR

**Comment by caub** [comment]
@gangstead 

- added a test for `prompt.get()` as a Promise
- updated README
- fixed `npm test` on recent node versions by updating vows (util.print was removed apparently in recent node versions, I didn't know it existed though:)

**Comment by caub** [comment]
do you have npm push access by any chance?

**Comment by gangstead** [comment]
Nope.  Sorry.

**Comment by caub** [comment]
@indexzero Hey, could you please, when you've a minute, do a `npm version minor` and a `npm publish`

We added a helpful promisified `prompt.get` in this PR

**Comment by apolopena** [comment]
Yeah this would really be nice.

**Comment by caub** [comment]
Can any one of the npm collaborators @jcrugzz @indutny @indexzero do something please? we need to sync this new updates on npm

**Pull request merged**
