### PR TITLE
Promise support

### PR DESCRIPTION
**Pull request by dhinklexo**
This adds in an initial take on Promise support using native node promises. 

In reference to #81, Promises have since become a standard pattern and well supported in Node LTS and later, and in addition no longer require additional abstractions such as Q or bluebird, and the spec itself has become reasonably standard (at least the usage of it here).

This maintains the callback Interface as a first-class-citizen and only falls back to Promises when callbacks aren't used, supporting both approaches without any additional deps. 

Also of mention, #176 which duplicates the upvoted ask in #81.

### CODE REVIEW

**Comment by kettanaito** [comment]
Any plans merging and publishing this?

**Comment by ifeanyiecheruo** [comment]
Awesome, every step away from nested callbacks is a step in the right direction.
However there's a compatibility problem with the change as it stands today.

Methods like prompt.get that used to return the prompt object now return a Promise, this will break clients that depend on the return value. 
e.g `prompt.start().get(...);` will no longer work.

A safer non-breaking approach would be to add new methods adjacent to the existing ones
eg.
`prompt.getPromise(...).then(...);`
or
```
pPrompt = prompt.promise;
pPromp.get(...).then(...);
```

**Comment by sunknudsen** [comment]
Any update on this PR? Many contemporary frameworks are now promise-based by default. Had to monkey patch `prompt` to support them.

**Comment by dhinklexo** [comment]
Unfortunately this project is quite dead it seems.

**Comment by sunknudsen** [comment]
> Unfortunately this project is quite dead it seems.

@dhinklexo The project does appear to have a backlog (issues and PRs). @indexzero is the project still alive? Are there any active maintainers?

**Comment by gangstead** [comment]
So I'm on the admin team for prompt because of a long ago accepted PR, but I don't really feel qualified to merge this in and I'm not able to release to npm.  What I can do is add @dhinklexo  as prompt admin so you can take ownership of this if you are interested.

**Comment by dhinklexo** [comment]
I unfortunately don't have the time to be an admin for this project or
update this PR.

**Comment by gangstead** [comment]
No problem just thought I'd offer

**Comment by caub** [comment]
Oh just noticed this PR

I did it differently in https://github.com/flatiron/prompt/pull/196, in a cheap but safe way, compared to refactoring .get and .getInput

**Comment by caub** [comment]
can be closed, promise support got added in #196 
thanks @dhinklexo

**Pull request closed without merging**
