### PR TITLE
Update vulnerable dependencies

### LINKED ISSUE #195: Please upgrade to winston 3.x to avoid licensing issue
Winston 2.x had a [dependency](https://github.com/winstonjs/winston/blob/2.x/package.json#L23) on the `cycle` npm package which has a [problematic](https://github.com/dscape/cycle/issues/1) licensing situation that they refuse to fix.

Would be nice if `prompt` can upgrade to Winston 3.x to avoid this issue.

### PR DESCRIPTION
**Pull request by mriedem**
- diff (via vows): https://github.com/advisories/GHSA-h6ch-v84p-w6p9

- async (via winston): https://github.com/advisories/GHSA-fwr7-v2mv-hh25

Related https://github.com/db-migrate/node-db-migrate/issues/779
Related 4736c828879af1b35acb83928e12db3d02754a59
Closes #195

### CODE REVIEW

**Comment by mriedem** [comment]
This will need work for the winston upgrade:

```
$ npm run test

> prompt@1.3.0 test
> vows test/prompt-test.js --spec

/home/osboxes/ibmq/prompt/lib/prompt.js:39
var logger = prompt.logger = new winston.Logger({
                             ^

TypeError: winston.Logger is not a constructor
    at Object.<anonymous> (/home/osboxes/ibmq/prompt/lib/prompt.js:39:30)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/osboxes/ibmq/prompt/test/prompt-test.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
```

**Comment by caub** [comment]
you probably need to remove the `new` https://github.com/winstonjs/winston/blob/master/CHANGELOG.md#if-a-tree-falls-in-the-forrest-does-it-make-a-log-edition

**Comment by bacali95** [comment]
Hello there, upgrading to winston@3 can be a bit challenging as it brings a ton of breaking changes.
@mriedem I did the migration as a task at work so I can help here if you don't mind?

**Comment by mriedem** [comment]
> Hello there, upgrading to winston@3 can be a bit challenging as it brings a ton of breaking changes. @mriedem I did the migration as a task at work so I can help here if you don't mind?

Hi, yes feel free to jump in here. Thanks!

**Comment by bacali95** [comment]
I have made this MR https://github.com/winstonjs/winston/pull/2112 a while ago and I was waiting for it to get merged and released, it is about backport the async vulnerability fox to the winston 2.x so intead of upgrading it to 3.x in this MR and suffer we can set the version to ^2.4.6 which has the fix

**Comment by mriedem** [comment]
> I have made this MR [winstonjs/winston#2112](https://github.com/winstonjs/winston/pull/2112) a while ago and I was waiting for it to get merged and released, it is about backport the async vulnerability fox to the winston 2.x so intead of upgrading it to 3.x in this MR and suffer we can set the version to ^2.4.6 which has the fix

Thank you! I'll close this PR. Can #195 also be closed?

**Pull request closed without merging**
