### PR TITLE
Missing colors/safe

### PR DESCRIPTION
**Pull request by piranna**
This fixes two places where colors/safe are not being used, giving `undefined` as output instead of the correct text.

### CODE REVIEW

**Comment by piranna** [comment]
Thank you! :-)

**Comment by gangstead** [comment]
Thanks to you as well.

**Comment by piranna** [comment]
You are welcome :-) When could be this published on npm?

**Comment by gangstead** [comment]
@indexzero Can we get a patch bump to `1.0.1`?

**Comment by brianantonelli** [comment]
would be really great if you could do a patch release to pick up this and other fixes

**Pull request merged**
